### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by bmcmahen** [duojs/watch#5]
I keep running into this error when trying to watch my app directory. Specifically, I'm using the duo command `duo -w -r client app.js > build.js`. I think part of the problem is that the `root` folder also contains the `components` folder, increasing the 'watched' files substantially... 

FYI I'm running node 0.11.13 on Yosemite dp5

```
path.js:0
(function (exports, require, module, __filename, __dirname) { // Copyright Joy
^
RangeError: Maximum call stack size exceeded
    at RegExp.exec (native)
    at splitPath (path.js:313:24)
    at exports.basename (path.js:465:11)
    at slug (/usr/local/lib/node_modules/duo/node_modules/duo-watch/lib/duo-watch.js:251:23)
    at find (/usr/local/lib/node_modules/duo/node_modules/duo-watch/lib/duo-watch.js:244:42)
    at Watch.manifest (/usr/local/lib/node_modules/duo/node_modules/duo-watch/lib/duo-watch.js:208:14)
    at Watch.deps (/usr/local/lib/node_modules/duo/node_modules/duo-watch/lib/duo-watch.js:101:10)
    at Watch.deps (/usr/local/lib/node_modules/duo/node_modules/duo-watch/lib/duo-watch.js:104:10)
    at Watch.deps (/usr/local/lib/node_modules/duo/node_modules/duo-watch/lib/duo-watch.js:104:10)
    at Watch.deps (/usr/local/lib/node_modules/duo/node_modules/duo-watch/lib/duo-watch.js:104:10)
    at Watch.deps (/usr/local/lib/node_modules/duo/node_modules/duo-watch/lib/duo-watch.js:104:10)
```

**Comment by matthewmueller** [comment]
yah... pretty sure it's related to: https://github.com/amasad/sane/issues/23

The files get opened regardless, even if you don't glob on a few of them.

**Comment by matthewmueller** [comment]
Haven't had time to look into it, but if you want to take a look: https://github.com/amasad/sane/issues/25#issuecomment-52567014

**Comment by bmcmahen** [comment]
Figured it was probably related, but thought it might also be related to the synchronous while loop that attempts to find the `root`, since that's where it seems to poop out on me.

**Comment by btknorr** [comment]
Any news on when this will be fixed?  duo --watch always fails with:

RangeError: Maximum call stack size exceeded
